[project]
name = "patch-opensci"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.12.0",
    "huggingface-hub>=0.36.2",
    "torch>=2.10.0",
    "transformers==4.48.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
